load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["jsar.go"],
    importpath = "vistarmedia.com/rules_js/js/tools/jsar",
    visibility = ["//visibility:public"],
)
